# Generated by Django 4.2.2 on 2023-06-17 07:46

import My_music_app.user_profile.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(15),
                            My_music_app.user_profile.validators.validator_user_name,
                        ]
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
