# Generated by Django 4.2.2 on 2023-06-22 14:48

import Car_collection_app.web.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Sports Car", "Sports Car"),
                            ("Pickup", "Pickup"),
                            ("Crossover", "Crossover"),
                            ("Minibus", "Minibus"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(20),
                        ]
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[Car_collection_app.web.validators.year_check]
                    ),
                ),
                ("image_Url", models.URLField()),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            Car_collection_app.web.validators.min_length,
                        ]
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "age",
                    models.IntegerField(
                        validators=[django.core.validators.MinLengthValidator(18)]
                    ),
                ),
                ("password", models.CharField(max_length=30)),
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(blank=True, max_length=30, null=True)),
                ("profile_picture", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
